apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arkouda-pvc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
  