apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arkouda
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arkouda-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: arkouda
  local:
    path: /mnt/arkouda
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arkouda-pvc
spec:
    storageClassName: arkouda
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
  