
## Admin Account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins
---


## Agent Account for Default Namespace

# Role for default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-default
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ServiceAccount for default namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
---
# RoleBinding for default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-default
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default

---

## Agent Account for Pachyderm Namespace

# Role for pachyderm namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-pachyderm
  namespace: pachyderm
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ServiceAccount for pachyderm namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: pachyderm
---
# RoleBinding for pachyderm namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pachyderm
  namespace: pachyderm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-pachyderm
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: pachyderm
